### ISSUE TITLE
What is the theme on readme?

### ISSUE THREAD

**Issue by felipevolpone** [oggy/vertical-motion#1]
Hey @oggy I've to say that this is a really nice plugin. Thank you :)) 
Can you tell me what is the color theme that you're using on the README.md?
Thanks!

**Comment by oggy** [comment]
Heh, thanks. It's a [custom set of styles](https://github.com/oggy/dotatom/blob/master/styles.less), which I wrote to match what I had made years ago for myself in Emacs. Feel free to steal it. :)
